set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR armv7)

set(CMAKE_C_COMPILER armv7-w64-mingw32-clang)
set(CMAKE_CXX_COMPILER armv7-w64-mingw32-clang++)
set(CMAKE_RC_COMPILER armv7-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH /usr/armv7-w64-mingw32)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
