
set(DEP_SDL_MIXER_VER "4aab76ed760ce521501e36b07962ba18d4a73e34")
download_dep_tarball(
	"SDL_mixer"
	"${DEP_SDL_MIXER_VER}"
	"https://github.com/libsdl-org/SDL_mixer/archive/${DEP_SDL_MIXER_VER}.tar.gz"
	"c1530fd974193cca7824c6137b45cca9e146566800e6ebeea007b45e9bf8874d"
)

file(REMOVE_RECURSE "${CMAKE_SOURCE_DIR}/lib/SDL_mixer/external/libxmp")
file(CREATE_LINK
	"${CMAKE_SOURCE_DIR}/lib/libxmp"
	"${CMAKE_SOURCE_DIR}/lib/SDL_mixer/external/libxmp"
	SYMBOLIC
)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

foreach(feature AIFF AU FLAC_DRFLAC FLAC_LIBFLAC GME MIDI_FLUIDSYNTH MIDI_TIMIDITY MP3_DRMP3 MP3_MPG123 OPUS VOC VORBIS_TREMOR VORBIS_VORBISFILE WAVPACK WAVPACK_DSD SAMPLES)
	set(SDLMIXER_${feature} OFF CACHE BOOL "" FORCE)
endforeach()

set(SDLMIXER_MOD_XMP ON CACHE BOOL "" FORCE)
set(SDLMIXER_MOD_XMP_SHARED OFF CACHE BOOL "" FORCE)
set(SDLMIXER_VENDORED ON CACHE BOOL "" FORCE)

add_subdirectory(lib/SDL_mixer EXCLUDE_FROM_ALL)
