
set(DEP_SDL_MIXER_VER "37b2f3325a0fb1e98ba265aa38826aa9e16624fb")
download_dep_tarball(
	"SDL_mixer"
	"${DEP_SDL_MIXER_VER}"
	"https://github.com/libsdl-org/SDL_mixer/archive/${DEP_SDL_MIXER_VER}.tar.gz"
	"10d621d89ba5741c7be3db586a0a178aca8e3790284bc50b26be37e33d38a9c6"
)

file(REMOVE_RECURSE "${CMAKE_SOURCE_DIR}/lib/SDL_mixer/external/libxmp")
file(CREATE_LINK
	"${CMAKE_SOURCE_DIR}/lib/libxmp"
	"${CMAKE_SOURCE_DIR}/lib/SDL_mixer/external/libxmp"
	SYMBOLIC
)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

foreach(feature AIFF AU FLAC_DRFLAC FLAC_LIBFLAC GME MIDI_FLUIDSYNTH MIDI_TIMIDITY MP3_DRMP3 MP3_MPG123 OPUS VOC VORBIS_TREMOR VORBIS_VORBISFILE WAVPACK WAVPACK_DSD SAMPLES)
	set(SDLMIXER_${feature} OFF CACHE BOOL "" FORCE)
endforeach()

set(SDLMIXER_MOD_XMP ON CACHE BOOL "" FORCE)
set(SDLMIXER_MOD_XMP_SHARED OFF CACHE BOOL "" FORCE)
set(SDLMIXER_VENDORED ON CACHE BOOL "" FORCE)

add_subdirectory(lib/SDL_mixer EXCLUDE_FROM_ALL)
