name: macOS

on:
  - push
  - pull_request

jobs:
  macos:
    name: Universal
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew update --auto-update
          brew install cmake ninja zip

      - name: Build Tensy
        run: |
          ./packaging/build.sh macos
          cd packaging/bin/macos && zip -r ../tensy-macos.zip -- tensy.app

      - name: Upload output
        uses: ./.github/actions/upload-output
        with:
          file: packaging/bin/tensy-macos.zip
          name: tensy-macos.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
