name: Web

permissions:
  contents: write
  pages: write
  id-token: write

on:
  - push
  - pull_request

jobs:
  web:
    name: Emscripten
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:latest
      env: { LANG: "C.UTF-8" }
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build xxd zip

      - name: Build Tensy
        run: |
          ./packaging/build.sh web
          cd packaging/bin/web && zip -r ../tensy-web.zip -- *

      - name: Upload output
        uses: ./.github/actions/upload-output
        with:
          file: packaging/bin/tensy-web.zip
          name: tensy-web.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GitHub Pages
        if: github.repository == 'rollerozxa/tensy'
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        if: github.repository == 'rollerozxa/tensy'
        uses: actions/upload-pages-artifact@v3
        with:
          path: packaging/bin/web/

      - name: Deploy to Pages
        if: github.repository == 'rollerozxa/tensy'
        id: deployment
        uses: actions/deploy-pages@v4
