name: Web

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
  pull_request:

jobs:
  web:
    name: Emscripten
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:latest
      env: { LANG: "C.UTF-8" }
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Run build
        run: |
          ./packaging/build-web.sh

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tensy-web
          path: packaging/bin/web/

      - name: Setup Pages
        if: github.repository == 'rollerozxa/tensy'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: github.repository == 'rollerozxa/tensy'
        uses: actions/upload-pages-artifact@v3
        with:
          path: packaging/bin/web/

      - name: Deploy to GitHub Pages
        if: github.repository == 'rollerozxa/tensy'
        id: deployment
        uses: actions/deploy-pages@v4
