name: Windows

on:
  push:
  pull_request:

jobs:
  windows:
    name: "${{ matrix.bits }}-bit"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Download toolchain
        run: |
          curl -L "https://github.com/mstorsjo/llvm-mingw/releases/download/20240619/llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64.tar.xz" | sudo tar xJvf - -C "/usr" --strip-components=1

      - name: Build Tensy
        run: |
          ./packaging/build-win.sh ${{ matrix.bits }}

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tensy-win-${{ matrix.bits }}
          path: packaging/bin/win${{ matrix.bits }}/tensy.exe
