name: Windows

on:
  - push
  - pull_request

env:
  # Check https://github.com/mstorsjo/llvm-mingw/releases for the latest version
  LLVM_MINGW_VERSION: 20251007

jobs:
  windows:
    name: "${{ matrix.display }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { display: "32-bit", bits: 32, toolchain: msvcrt }
          - { display: "64-bit", bits: 64, toolchain: ucrt }
          - { display: "32-bit (ARM)", bits: arm32, toolchain: msvcrt }
          - { display: "64-bit (ARM)", bits: arm64, toolchain: ucrt }
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Download toolchain
        run: |
          curl -L "https://github.com/mstorsjo/llvm-mingw/releases/download/${{ env.LLVM_MINGW_VERSION }}/llvm-mingw-${{ env.LLVM_MINGW_VERSION }}-${{ matrix.toolchain }}-ubuntu-22.04-x86_64.tar.xz" | sudo tar xJvf - -C "/usr" --strip-components=1

      - name: Build Tensy
        run: |
          ./packaging/build.sh win ${{ matrix.bits }}

      - name: Upload output
        uses: ./.github/actions/upload-output
        with:
          file: packaging/bin/win${{ matrix.bits }}/tensy.exe
          name: tensy-win${{ matrix.bits }}.exe
          repo_token: ${{ secrets.GITHUB_TOKEN }}
